# Generated by Django 5.1.3 on 2024-12-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='Not Completed', max_length=20),
            preserve_default=False,
        ),
    ]
